INSERT INTO "categories" ("name") VALUES
        ('Electronics'),
        ('Clothing'),
        ('Home & Kitchen'),
        ('Sports & Outdoors'),
        ('Books'),
        ('Beauty & Personal Care'),
        ('Toys & Games'),
        ('Automotive'),
        ('Grocery'),
        ('Furniture'),
        ('Jewelry'),
        ('Pet Supplies'),
        ('Tools & Hardware'),
        ('Health & Wellness'),
        ('Garden & Outdoor'),
        ('Music & Instruments'),
        ('Art & Crafts'),
        ('Baby Products'),
        ('Office Supplies'),
        ('Shoes');
